# Generated by Django 5.2.6 on 2025-09-07 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('networth', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('matchesplayed', models.PositiveIntegerField(default=0)),
                ('winningpercentage', models.FloatField(default=0)),
                ('networth', models.FloatField(default=0)),
                ('spouse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to='academy.player')),
            ],
        ),
        migrations.CreateModel(
            name='TagTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('matchesplayed', models.PositiveIntegerField(default=0)),
                ('winningpercentage', models.FloatField(default=0)),
                ('networth', models.FloatField(default=0)),
                ('player_1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_1', to='academy.player')),
                ('player_2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_2', to='academy.player')),
            ],
        ),
    ]
