# Generated by Django 5.2.6 on 2025-09-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='image_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='image_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tagteam',
            name='image_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
