# Generated by Django 5.2.6 on 2025-09-07 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_band_image_url_player_image_url_tagteam_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='band',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player_band', to='academy.band'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagteam',
            name='band',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tagteam_band', to='academy.band'),
            preserve_default=False,
        ),
    ]
