# Generated by Django 5.2.6 on 2025-09-07 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_player_band_tagteam_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_band', to='academy.band'),
        ),
        migrations.AlterField(
            model_name='tagteam',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagteam_band', to='academy.band'),
        ),
    ]
