# Generated by Django 5.2.6 on 2025-09-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_alter_player_band_alter_tagteam_band'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagteam',
            name='image_url',
        ),
    ]
