# Generated by Django 5.2.6 on 2025-09-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_remove_tagteam_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagteam',
            name='band',
        ),
        migrations.RemoveField(
            model_name='tagteam',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='tagteam',
            name='player_2',
        ),
    ]
