# Generated by Django 5.2.6 on 2025-09-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_remove_tagteam_band_remove_tagteam_player_1_and_more'),
        ('match', '0002_alter_singlematch_player_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagTeam',
        ),
    ]
