# Generated by Django 5.2.6 on 2025-09-08 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_delete_tagteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academy.player')),
            ],
        ),
    ]
