# Generated by Django 5.2.6 on 2025-09-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_championship'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='image_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
