# Generated by Django 5.2.6 on 2025-09-08 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_championship_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.player'),
        ),
    ]
