# Generated by Django 5.2.6 on 2025-09-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_alter_championship_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='hike',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
