# Generated by Django 5.2.6 on 2025-09-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_championship_hike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='hike',
            field=models.FloatField(),
        ),
    ]
