# Generated by Django 5.2.6 on 2025-09-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_alter_player_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
