# Generated by Django 5.2.6 on 2025-09-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='emoji',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
