# Generated by Django 5.2.6 on 2025-09-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_band_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='emoji',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
