# Generated by Django 5.2.6 on 2025-09-21 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0019_auction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionshipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateTimeField()),
                ('ended_on', models.DateTimeField(blank=True, null=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='academy.championship')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.player')),
            ],
        ),
    ]
