# Generated by Django 5.2.6 on 2025-09-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0020_championshiphistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championship',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='championshiphistory',
            options={'ordering': ['-started_on']},
        ),
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='championship',
            name='updated_on',
            field=models.DateTimeField(),
        ),
    ]
