# Generated by Django 5.2.6 on 2025-09-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0021_alter_championship_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
