# Generated by Django 5.2.6 on 2025-09-07 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_remove_tagteam_band_remove_tagteam_player_1_and_more'),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlematch',
            name='player_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_match_player_1', to='academy.player'),
        ),
        migrations.AlterField(
            model_name='singlematch',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_match_player_2', to='academy.player'),
        ),
        migrations.AlterField(
            model_name='singlematch',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_match_winner', to='academy.player'),
        ),
        migrations.DeleteModel(
            name='TagTeamMatch',
        ),
    ]
