# Generated by Django 5.2.6 on 2025-09-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_remove_notification_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlematch',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
