# Generated by Django 5.2.6 on 2025-09-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_singlematch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
