# Generated by Django 5.2.6 on 2025-09-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_notification_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlematch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
