# Generated by Django 5.2.6 on 2025-09-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_tournament_singlematch_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
