# Generated by Django 5.2.6 on 2025-09-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_tournament_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
