# Generated by Django 5.2.6 on 2025-09-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_tournament_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_main_tournament',
            field=models.BooleanField(default=False),
        ),
    ]
