# Generated by Django 5.2.6 on 2025-09-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_tournament_is_main_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='image_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
