# Generated by Django 5.2.6 on 2025-09-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_tournament_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_auto_play_tournament',
            field=models.BooleanField(default=False),
        ),
    ]
