# Generated by Django 5.2.6 on 2025-09-26 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0012_tournament_is_auto_play_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='is_auto_play_tournament',
        ),
    ]
