# Generated by Django 5.2.6 on 2025-10-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0013_remove_tournament_is_auto_play_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlematch',
            name='is_championship_match',
            field=models.BooleanField(default=False),
        ),
    ]
